### ISSUE TITLE
Configuration Name is not same then entered

### ISSUE THREAD

**Issue by schettgen** [sms77io/node-red-contrib-sms77#5]
I'm using SMS sent node and choosen my configuration

I created 2 configuration to distinguish between testing and live later. 

![image](https://user-images.githubusercontent.com/76427220/210179527-178098b0-da75-471e-bd49-971508f410cc.png)

I would expect to see here the entered name of the configuration instead of the hash 

![image](https://user-images.githubusercontent.com/76427220/210179560-6dce8856-26e1-4035-90c6-860f940d47ed.png)

**Comment by matthiez** [comment]
Hi @schettgen,
thanks for your suggestion.
I have just published v3.2.2, where this has been fixed.

Hope this helps you!
